In [1]:
import tabula
import pdfplumber
import pandas as pd
import numpy as np

In [2]:
pdf_path = "guardian01.pdf"
# pdf_path = "pdf//5.pdf"

In [3]:
def extract_text_coordinates(pdf_path):
    text_list = []
    with pdfplumber.open(pdf_path) as pdf:
        # Iterate through each page of the PDF
        for page_number in range(len(pdf.pages)):
            page = pdf.pages[page_number]
            page_number = page_number + 1
            # Extract the text content and its coordinates
            for element in page.extract_words(x_tolerance=1, y_tolerance=1, keep_blank_chars=True):
                text_dict = {}
                text = element["text"]
                x, y = element["x0"], element["top"]
                
                text_cord = f"Page {page_number + 1}: Text: {text} Coordinates: X={x}, Y={y}"
                text_dict.update({'page':page_number, 'text':text,'cordx':x,'cordy':y})
                text_list.append(text_dict)
    return text_list

text_list = extract_text_coordinates(pdf_path)

In [4]:
text_list

[{'page': 1,
  'text': 'P627402800E',
  'cordx': 110.4,
  'cordy': 5.2835999999999785},
 {'page': 1,
  'text': 'P627402800E',
  'cordx': 31.6801,
  'cordy': 12.72359999999992},
 {'page': 1,
  'text': 'PO BOX 981572',
  'cordx': 94.6801,
  'cordy': 28.301400000000058},
 {'page': 1,
  'text': 'EL PASO, TX  79998-1572',
  'cordx': 94.6801,
  'cordy': 38.5014000000001},
 {'page': 1,
  'text': ' 190114   ',
  'cordx': 271.92023408,
  'cordy': 69.48339999999996},
 {'page': 1,
  'text': 'If you have any',
  'cordx': 294.84,
  'cordy': 77.02140000000009},
 {'page': 1,
  'text': '(800) 541-7846',
  'cordx': 381.1200307624,
  'cordy': 77.86170000000016},
 {'page': 1,
  'text': 'Electronic Service Requested',
  'cordx': 94.6801,
  'cordy': 80.02130000000011},
 {'page': 1,
  'text': 'questions contact:',
  'cordx': 294.84,
  'cordy': 88.18160000000012},
 {'page': 1,
  'text': 'WWW.GUARDIANANYTIME.COM',
  'cordx': 381.1200307624,
  'cordy': 88.30150000000015},
 {'page': 1,
  'text': 'ALL FOR AADC 840',
  'cordx': 170.75986395799998,
  'cordy': 109.34399999999994},
 {'page': 1,
  'text': 'Claim Number:',
  'cordx': 294.84,
  'cordy': 116.02140000000009},
 {'page': 1,
  'text': '37856F16600',
  'cordx': 383.40012624639996,
  'cordy': 116.74171300000012},
 {'page': 1,
  'text': '21902 0.5738 AB 0.504',
  'cordx': 49.9199,
  'cordy': 118.34399999999994},
 {'page': 1,
  'text': 'ATFTDDFAFTATFDDFFAAFTADDFTAFADTFAAAFDTFDAATDTATTTAAFDFFTAAFDAAAFD',
  'cordx': 49.8,
  'cordy': 125.8667999999999},
 {'page': 1,
  'text': 'Employee Name:',
  'cordx': 294.84000000000003,
  'cordy': 127.30150000000015},
 {'page': 1,
  'text': 'JARED MELLOR',
  'cordx': 383.4001262464,
  'cordy': 127.90150000000017},
 {'page': 1,
  'text': 'Patient Name:',
  'cordx': 294.84000000000003,
  'cordy': 138.5816000000002},
 {'page': 1,
  'text': 'KOLSEN MELLOR',
  'cordx': 383.4001262464,
  'cordy': 138.46167800000023},
 {'page': 1,
  'text': 'JEFFREY T WELCH, DMD',
  'cordx': 49.68010000000001,
  'cordy': 144.57514000000003},
 {'page': 1,
  'text': '385',
  'cordx': 247.319909575,
  'cordy': 147.28869999999995},
 {'page': 1,
  'text': 'Relationship:',
  'cordx': 294.84000000000003,
  'cordy': 149.8616780000002},
 {'page': 1,
  'text': 'SON',
  'cordx': 383.4001262464,
  'cordy': 149.7413650000002},
 {'page': 1,
  'text': 'BURG CHILDRENS DENTISTRY AND O',
  'cordx': 49.68010000000001,
  'cordy': 151.29506000000003},
 {'page': 1,
  'text': '275 W 200 N STE 175',
  'cordx': 49.6801,
  'cordy': 158.49504000000002},
 {'page': 1,
  'text': 'Patient Account No.:121748878',
  'cordx': 294.84000000000003,
  'cordy': 161.02146500000015},
 {'page': 1,
  'text': 'LINDON, UT  84042-5018',
  'cordx': 49.68010000000001,
  'cordy': 165.69504000000006},
 {'page': 1,
  'text': 'Plan Number:',
  'cordx': 294.84000000000003,
  'cordy': 172.30158700000015},
 {'page': 1,
  'text': '00025210',
  'cordx': 383.4001262464,
  'cordy': 172.18166500000018},
 {'page': 1,
  'text': 'Planholder:',
  'cordx': 294.84000000000003,
  'cordy': 183.58166500000016},
 {'page': 1,
  'text': 'ALARM.COM, INC.',
  'cordx': 383.4001262464,
  'cordy': 183.46174300000018},
 {'page': 1,
  'text': 'Provider:',
  'cordx': 294.84000000000003,
  'cordy': 194.86174300000016},
 {'page': 1,
  'text': 'JEFFREY T WELCH, DMD',
  'cordx': 383.4001262464,
  'cordy': 194.74143000000015},
 {'page': 1,
  'text': 'Date:',
  'cordx': 294.84000000000003,
  'cordy': 206.0215300000001},
 {'page': 1,
  'text': '06/16/23',
  'cordx': 383.4001262464,
  'cordy': 206.7414520000001},
 {'page': 1,
  'text': 'EXPLANATION OF BENEFITS - THIS IS NOT A BILL',
  'cordx': 138.24,
  'cordy': 220.29060000000004},
 {'page': 1,
  'text': 'Important! Save this statement for tax purposes.',
  'cordx': 170.40018563040002,
  'cordy': 238.57870000000003},
 {'page': 1, 'text': 'Line ', 'cordx': 18.8398, 'cordy': 256.1286},
 {'page': 1,
  'text': 'Submitted',
  'cordx': 72.3602,
  'cordy': 255.40859999999998},
 {'page': 1, 'text': 'Alt', 'cordx': 155.16, 'cordy': 255.40859999999998},
 {'page': 1, 'text': 'Tooth', 'cordx': 182.64, 'cordy': 255.40859999999998},
 {'page': 1,
  'text': 'Date of',
  'cordx': 225.48022351375,
  'cordy': 255.40859999999998},
 {'page': 1,
  'text': 'Submitted',
  'cordx': 275.039983970775,
  'cordy': 255.40859999999998},
 {'page': 1,
  'text': 'Considered',
  'cordx': 328.91992700950004,
  'cordy': 255.40859999999998},
 {'page': 1,
  'text': 'Covered',
  'cordx': 391.31990537425,
  'cordy': 255.40859999999998},
 {'page': 1,
  'text': 'Deductible',
  'cordx': 437.63988743325007,
  'cordy': 255.40859999999998},
 {'page': 1,
  'text': 'Coverage',
  'cordx': 490.679876555775,
  'cordy': 255.40859999999998},
 {'page': 1, 'text': 'Benefit', 'cordx': 548.76, 'cordy': 255.40859999999998},
 {'page': 1, 'text': 'No.', 'cordx': 21.719875162250002, 'cordy': 265.24852},
 {'page': 1,
  'text': 'ADA Codes/Description',
  'cordx': 48.839863972500005,
  'cordy': 264.52851999999996},
 {'page': 1,
  'text': 'Code',
  'cordx': 151.5600033595,
  'cordy': 264.52851999999996},
 {'page': 1,
  'text': 'No.',
  'cordx': 186.96031734874998,
  'cordy': 264.52851999999996},
 {'page': 1,
  'text': 'Service',
  'cordx': 225.36030180827498,
  'cordy': 264.52851999999996},
 {'page': 1,
  'text': 'Charge',
  'cordx': 279.960294105775,
  'cordy': 264.52851999999996},
 {'page': 1,
  'text': 'Charge',
  'cordx': 335.76016415675,
  'cordy': 264.52851999999996},
 {'page': 1,
  'text': 'Charge',
  'cordx': 392.99998498325004,
  'cordy': 264.52851999999996},
 {'page': 1,
  'text': 'Amount',
  'cordx': 442.3199708965001,
  'cordy': 264.52851999999996},
 {'page': 1,
  'text': 'Percent',
  'cordx': 493.919717832525,
  'cordy': 264.52851999999996},
 {'page': 1,
  'text': 'Amount',
  'cordx': 547.1998391022499,
  'cordy': 264.52851999999996},
 {'page': 1, 'text': '1', 'cordx': 24.2398, 'cordy': 277.84860000000003},
 {'page': 1,
  'text': 'D2332/Composite 3 Sr',
  'cordx': 39.8398,
  'cordy': 277.1286},
 {'page': 1, 'text': '09', 'cordx': 189.72, 'cordy': 277.84860000000003},
 {'page': 1,
  'text': '06/14/23',
  'cordx': 224.8801103900001,
  'cordy': 277.1286},
 {'page': 1, 'text': '172.00', 'cordx': 297.9601599650001, 'cordy': 277.1286},
 {'page': 1, 'text': '102.00', 'cordx': 355.7996042900001, 'cordy': 277.1286},
 {'page': 1,
  'text': '102.00',
  'cordx': 405.3598168750001,
  'cordy': 277.848522},
 {'page': 1, 'text': '90%', 'cordx': 498.83972099000016, 'cordy': 277.848522},
 {'page': 1, 'text': '91.80', 'cordx': 574.0806029400002, 'cordy': 277.1286},
 {'page': 1, 'text': '2', 'cordx': 24.2398, 'cordy': 286.0086},
 {'page': 1,
  'text': 'D2332/Composite 3 Sr',
  'cordx': 39.8398,
  'cordy': 285.28860000000003},
 {'page': 1, 'text': '10', 'cordx': 189.72, 'cordy': 286.0086},
 {'page': 1,
  'text': '06/14/23',
  'cordx': 224.8801103900001,
  'cordy': 285.28860000000003},
 {'page': 1,
  'text': '172.00',
  'cordx': 297.9601599650001,
  'cordy': 285.28860000000003},
 {'page': 1,
  'text': '102.00',
  'cordx': 355.7996042900001,
  'cordy': 285.28860000000003},
 {'page': 1,
  'text': '102.00',
  'cordx': 405.3598168750001,
  'cordy': 286.008522},
 {'page': 1, 'text': '90%', 'cordx': 498.83972099000016, 'cordy': 286.008522},
 {'page': 1,
  'text': '91.80',
  'cordx': 574.0806029400002,
  'cordy': 285.28860000000003},
 {'page': 1, 'text': 'TOTALS', 'cordx': 223.08, 'cordy': 294.615},
 {'page': 1, 'text': '344.00', 'cordx': 297.36, 'cordy': 294.28860000000003},
 {'page': 1, 'text': '204.00', 'cordx': 355.8, 'cordy': 294.28860000000003},
 {'page': 1,
  'text': '204.00',
  'cordx': 405.36017625507003,
  'cordy': 294.28860000000003},
 {'page': 1,
  'text': '20.40',
  'cordx': 497.04019562499997,
  'cordy': 294.28860000000003},
 {'page': 1, 'text': '183.60', 'cordx': 570.0, 'cordy': 294.28860000000003},
 {'page': 1, 'text': ' ', 'cordx': 22.6801, 'cordy': 306.28860000000003},
 {'page': 1, 'text': 'BENEFIT SUMMARY', 'cordx': 444.0, 'cordy': 308.055},
 {'page': 1,
  'text': 'TOTAL BENEFIT PAYABLE.........',
  'cordx': 389.4,
  'cordy': 319.335},
 {'page': 1, 'text': '$183.60', 'cordx': 561.36, 'cordy': 319.335},
 {'page': 1,
  'text': 'HIGHER ALLOWABLE..................',
  'cordx': 389.400042369,
  'cordy': 329.89468700000003},
 {'page': 1, 'text': '$204.00', 'cordx': 561.36, 'cordy': 330.615},
 {'page': 1,
  'text': 'PAID BY OTHER INSURANCE.....',
  'cordx': 389.400042369,
  'cordy': 339.6151},
 {'page': 1, 'text': '$0.00', 'cordx': 570.480336246, 'cordy': 341.89479},
 {'page': 1,
  'text': 'ADJUSTMENTS...............................',
  'cordx': 389.40004236899995,
  'cordy': 350.89479},
 {'page': 1, 'text': '$0.00', 'cordx': 570.47297051154, 'cordy': 350.89479},
 {'page': 1,
  'text': 'TOTAL BENEFIT PAID..................',
  'cordx': 389.40004236899995,
  'cordy': 362.05499},
 {'page': 1,
  'text': '$183.60',
  'cordx': 561.3562572487499,
  'cordy': 362.05499},
 {'page': 1,
  'text': "PATIENT'S RESPONSIBILITY",
  'cordx': 389.4,
  'cordy': 373.335},
 {'page': 1,
  'text': '$20.40',
  'cordx': 565.920125754,
  'cordy': 373.33500000000004},
 {'page': 1,
  'text': '....................................',
  'cordx': 389.4,
  'cordy': 383.535},
 {'page': 1,
  'text': 'Year to Date Information',
  'cordx': 18.1199,
  'cordy': 394.3014},
 {'page': 1,
  'text': 'You have reached $342.60 of your individual maximum of $1,750.00 for benefit year beginning 01/01/23.',
  'cordx': 18.1199,
  'cordy': 405.495},
 {'page': 1, 'text': 'Remarks:', 'cordx': 18.1199, 'cordy': 418.455},
 {'page': 1,
  'text': 'REIMBURSEMENT HAS BEEN DETERMINED USING A STRATOSE/TDA FEE SCHEDULE',
  'cordx': 18.1199,
  'cordy': 430.095},
 {'page': 1,
  'text': 'You have used     $0.00 of your personal Maximum Rollover Account.   $350.00 remains in your account',
  'cordx': 18.1199,
  'cordy': 441.495},
 {'page': 1,
  'text': 'Payment Amount: $183.60  Payee:JEFFREY T WELCH, DMD 854364176',
  'cordx': 18.1199,
  'cordy': 455.2614},
 {'page': 1, 'text': 'Comments', 'cordx': 18.1199, 'cordy': 468.135},
 {'page': 1,
  'text': 'Current Dental Terminology © 2021 American Dental Association. All rights reserved.',
  'cordx': 18.1199,
  'cordy': 476.895},
 {'page': 1,
  'text': 'Log on to www.GuardianAnytime.com  for instant access to clinical policy guidelines and benefits information for Guardian members. Verify eligibility, view',
  'cordx': 18.12017438699999,
  'cordy': 488.7751},
 {'page': 1,
  'text': 'benefits, check claim status and more!',
  'cordx': 18.12017438699999,
  'cordy': 497.7751},
 {'page': 1,
  'text': 'Fraud affects all of us!  If you know or suspect that fraud is taking place, call us on our exclusive FRAUD HOTLINE 800-477-5908, Monday through ',
  'cordx': 18.12017438699999,
  'cordy': 507.01533},
 {'page': 1,
  'text': 'Friday, 9:00 AM to 4:00 PM (Eastern Time), or visit our web site at http://www.GuardianAnytime.com (select "Contact Us" and then "Report Fraud").',
  'cordx': 18.12017438699999,
  'cordy': 517.21533},
 {'page': 1, 'text': ' ', 'cordx': 18.12017438699999, 'cordy': 537.85513},
 {'page': 1, 'text': 'EOB-DE1-09', 'cordx': 18.1199, 'cordy': 765.2886},
 {'page': 1,
  'text': '        2 FO 1           20912 VNE',
  'cordx': 14.403799999999999,
  'cordy': 9.182313641940482},
 {'page': 2,
  'text': 'P627402800V',
  'cordx': 110.4,
  'cordy': 5.2835999999999785},
 {'page': 2,
  'text': 'P627402800V',
  'cordx': 31.6801,
  'cordy': 12.72359999999992},
 {'page': 2,
  'text': 'PO BOX 981572',
  'cordx': 94.6801,
  'cordy': 28.301400000000058},
 {'page': 2,
  'text': 'EL PASO, TX  79998-1572',
  'cordx': 94.6801,
  'cordy': 38.5014000000001},
 {'page': 2,
  'text': '    ',
  'cordx': 271.92023408,
  'cordy': 69.48339999999996},
 {'page': 2,
  'text': 'Electronic Service Requested',
  'cordx': 94.6801,
  'cordy': 80.02130000000011},
 {'page': 2,
  'text': 'ALL FOR AADC 840',
  'cordx': 170.75986395799998,
  'cordy': 109.34399999999994},
 {'page': 2,
  'text': '21902 0.5738 AB 0.504',
  'cordx': 49.9199,
  'cordy': 118.34399999999994},
 {'page': 2,
  'text': 'ATFTDDFAFTATFDDFFAAFTADDFTAFADTFAAAFDTFDAATDTATTTAAFDFFTAAFDAAAFD',
  'cordx': 49.8,
  'cordy': 125.8667999999999},
 {'page': 2,
  'text': 'JEFFREY T WELCH, DMD',
  'cordx': 49.68010000000001,
  'cordy': 144.57514000000003},
 {'page': 2,
  'text': '385',
  'cordx': 247.319909575,
  'cordy': 147.28869999999995},
 {'page': 2,
  'text': 'BURG CHILDRENS DENTISTRY AND O',
  'cordx': 49.68010000000001,
  'cordy': 151.29506000000003},
 {'page': 2,
  'text': '275 W 200 N STE 175',
  'cordx': 49.6801,
  'cordy': 158.49504000000002},
 {'page': 2,
  'text': 'LINDON, UT  84042-5018',
  'cordx': 49.68010000000001,
  'cordy': 165.69504000000006},
 {'page': 2, 'text': '10 Hudson Yards', 'cordx': 342.12, 'cordy': 595.095},
 {'page': 2,
  'text': 'CHECK NO: 188544665',
  'cordx': 445.68,
  'cordy': 596.8614},
 {'page': 2, 'text': 'New York, NY 10001', 'cordx': 342.12, 'cordy': 604.095},
 {'page': 2,
  'text': 'CHECK DATE: 06/16/23',
  'cordx': 445.68,
  'cordy': 610.3014000000001},
 {'page': 2, 'text': 'AMOUNT', 'cordx': 488.4000390352, 'cordy': 625.3015},
 {'page': 2, 'text': '51-44', 'cordx': 427.2, 'cordy': 626.49},
 {'page': 2, 'text': '119', 'cordx': 429.7199212548, 'cordy': 636.9298},
 {'page': 2, 'text': '****$183.60', 'cordx': 459.12, 'cordy': 638.0214},
 {'page': 2, 'text': 'PAY', 'cordx': 49.91950020000007, 'cordy': 649.3012},
 {'page': 2,
  'text': 'One Hundred Eighty Three & 60/100 Dollars',
  'cordx': 74.39782837705638,
  'cordy': 649.3012},
 {'page': 2,
  'text': 'Void unless presented ',
  'cordx': 470.76,
  'cordy': 653.6886},
 {'page': 2,
  'text': 'within 180 days',
  'cordx': 482.3998500725,
  'cordy': 662.80852},
 {'page': 2, 'text': 'TO THE', 'cordx': 49.9199, 'cordy': 666.5814},
 {'page': 2,
  'text': 'JEFFREY T WELCH, DMD',
  'cordx': 114.119883328,
  'cordy': 668.86151},
 {'page': 2, 'text': 'ORDER OF', 'cordx': 49.9199, 'cordy': 677.7412},
 {'page': 2,
  'text': 'BANK OF AMERICA',
  'cordx': 36.8398,
  'cordy': 705.2099000000001},
 {'page': 2,
  'text': '150 WINDSOR STREET, HARTFORD, CT 06120',
  'cordx': 36.8398,
  'cordy': 712.04974},
 {'page': 2,
  'text': 'C188544665C',
  'cordx': 94.91999359245003,
  'cordy': 763.9888},
 {'page': 2,
  'text': 'A011900445A',
  'cordx': 202.92002520884995,
  'cordy': 763.9888},
 {'page': 2, 'text': '40355C', 'cordx': 355.92000346094994, 'cordy': 763.9888},
 {'page': 2,
  'text': '       411091 2 FO 2           20912 VNE',
  'cordx': 14.403799999999999,
  'cordy': 9.182384986079}]

In [5]:
dfs = []
x2 = 0
y2 = 0
for text_d in text_list:
    x = text_d['cordx']
    y = text_d['cordy']
    if x2<x:
        x2 = text_d['cordx']
    if y2<y:
        y2 = text_d['cordy']    
x2 = x2+20
y2 = y2+20
print("YYYY", y2)
for i in range(len(text_list)):
    x1 = y1 = ''
    if 'Line' in text_list[i]['text']:
        print("Line", text_list[i]['text'])
        x1 = text_list[i]['cordx']
        y1 = text_list[i]['cordy']
        page_number = text_list[i]['page']
        for j in range(i,len(text_list)):
            
            if page_number == text_list[j]['page']:
                if 'BENEFIT SUMMARY' in text_list[j]['text']:
                    print("Bene", text_list[j]['text'])
                    print("PAG", text_list[j]['page'] )
                    page = int(text_list[j]['page'])
                    y2 = text_list[j]['cordy']
                    print(f"x1 = {x1}, y1 = {y1}, x2 = {x2}, y2 = {y2}")
                    tabula_dfs = tabula.read_pdf(pdf_path, guess=False, pages=page , stream=True, encoding="utf-8",
                                     area=(y1, x1, y2, x2), multiple_tables=True)
                    df_filled = tabula_dfs[0].fillna('')
                    dfs.append(df_filled[1:])
                    break
            
            if page_number == text_list[j]['page']:
                if '10 Hudson Yards' in text_list[j]['text']:
                    print("10 Hudson", text_list[j]['text'])
                    print("PAG", text_list[j]['page'] )
                    page = int(text_list[j]['page'])
                    y2 = text_list[j]['cordy']
                    print(f"x1 = {x1}, y1 = {y1}, x2 = {x2}, y2 = {y2}")
                    tabula_dfs = tabula.read_pdf(pdf_path, guess=False, pages=page , stream=True, encoding="utf-8",
                                     area=(y1, x1, y2, x2), multiple_tables=True)
                    df_filled = tabula_dfs[0].fillna('')
                    dfs.append(df_filled[1:])
                    break
                
            
            if page_number == text_list[j]['page']:
#                 if 'BENEFIT SUMMARY' not in text_list[j]['text'] and '10 Hudson Yards' not in text_list[j]['text']:
                if 'VNE' in text_list[j]['text']:
                    y2 = 780
                    page = int(text_list[j]['page'])
                    print(f"x1 = {x1}, y1 = {y1}, x2 = {x2}, y2 = {y2}")
                    tabula_dfs = tabula.read_pdf(pdf_path, guess=False, pages=page , stream=True, encoding="utf-8",
                                     area=(y1, x1, y2, x2), multiple_tables=True)
                    df_filled = tabula_dfs[0].fillna('')
                    dfs.append(df_filled[1:])
                    break

YYYY 785.2886
Line Line
Bene BENEFIT SUMMARY
PAG 1
x1 = 18.8398, y1 = 256.1286, x2 = 594.0806029400002, y2 = 308.055

Got stderr: Jul 12, 2023 3:35:22 PM org.apache.pdfbox.pdmodel.font.PDSimpleFont readEncoding
WARNING: Unknown encoding: BuiltIn
Jul 12, 2023 3:35:22 PM org.apache.pdfbox.pdmodel.font.PDSimpleFont readEncoding
WARNING: Unknown encoding: BuiltIn
Jul 12, 2023 3:35:22 PM org.apache.pdfbox.pdmodel.font.PDSimpleFont readEncoding
WARNING: Unknown encoding: BuiltIn
Jul 12, 2023 3:35:22 PM org.apache.pdfbox.pdmodel.font.PDSimpleFont readEncoding
WARNING: Unknown encoding: BuiltIn
Jul 12, 2023 3:35:22 PM org.apache.pdfbox.pdmodel.font.PDSimpleFont readEncoding
WARNING: Unknown encoding: BuiltIn
Jul 12, 2023 3:35:22 PM org.apache.pdfbox.pdmodel.font.PDSimpleFont readEncoding
WARNING: Unknown encoding: BuiltIn

In [8]:
print(len(dfs))
dfs[0]

1

,Line,Submitted,Alt,Tooth,Date of,Submitted.1,Considered,Covered,Deductible,Coverage,Benefit
1,1,D2332/Composite 3 Sr,,09,06/14/23,172.00,102.00,102.00,,90%,91.80
2,2,D2332/Composite 3 Sr,,10,06/14/23,172.00,102.00,102.00,,90%,91.80
3,,,,,TOTALS,344.00,204.00,204.00,,20.40,183.60

In [9]:
search_string = 'TOTALS'
final = []
stack_list = []
for d in dfs:
    last_row = d.iloc[-1]
    col = last_row[4]
    
    print(col)
    print(type(col))
    if 'TOTALS' in col:
        print("In the if")
        if stack_list:
            new_df = pd.concat(stack_list + [d] , axis=0)
            final.append(new_df)
            stack_list = []
        else:
            final.append(d)    
    else:
        stack_list.append(d)

TOTALS
<class 'str'>
In the if

In [14]:
print(len(final))

1

In [15]:
tdfs =[]

for df in final:
    df = df[~df.apply(lambda row: row.astype(str).str.contains('TOTALS', case=False)).any(axis=1)]
    df.rename(columns={'Date of': 'Date'}, inplace=True)
    df.fillna('', inplace=True)
    df.drop('Line', axis=1, inplace=True)
    tdfs.append(df)

C:\Users\pytho\AppData\Local\Temp\ipykernel_18024\98455734.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.rename(columns={'Date of': 'Date'}, inplace=True)
C:\Users\pytho\AppData\Local\Temp\ipykernel_18024\98455734.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.fillna('', inplace=True)
C:\Users\pytho\AppData\Local\Temp\ipykernel_18024\98455734.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.drop('Line', axis=1, inplace=True)

In [16]:
tdfs[0]

,Submitted,Alt,Tooth,Date,Submitted.1,Considered,Covered,Deductible,Coverage,Benefit
1,D2332/Composite 3 Sr,,09,06/14/23,172.00,102.00,102.00,,90%,91.80
2,D2332/Composite 3 Sr,,10,06/14/23,172.00,102.00,102.00,,90%,91.80

In [17]:
new_dict = []
for td in tdfs:
    tab = td.to_dict(orient='records')
    for i in range(len(tab)):
        new_dict.append(tab[i])
    
#     new_dict.append(td.to_dict(orient='records'))

In [18]:
print(len(new_dict))

2

In [19]:
tab_dict = []

change_keys = [("Alt","AltCode"),("Tooth", "ToothNo"),("Date", "ServiceDate"), ("Submitted.1", "SubmittedCharges"),
               ("Benefit", "PayableAmount"), ("Considered", "ActualAllowed"),
               ("Deductible", "ContractualObligations"),("Covered", "CoveredCharge"),("Coverage", "CoveragePercent")]
for d in new_dict:
    for k in change_keys:
        old_key = k[0]
        new_key = k[1]
        value = d[old_key]
        d[new_key] = value
        
        
    for k in change_keys:
        del d[k[0]]
    print("D",d)
    tab_dict.append(d)

D {'Submitted': 'D2332/Composite 3 Sr', 'AltCode': '', 'ToothNo': '09', 'ServiceDate': '06/14/23', 'SubmittedCharges': '172.00', 'PayableAmount': '91.80', 'ActualAllowed': '102.00', 'ContractualObligations': '', 'CoveredCharge': '102.00', 'CoveragePercent': '90%'}
D {'Submitted': 'D2332/Composite 3 Sr', 'AltCode': '', 'ToothNo': '10', 'ServiceDate': '06/14/23', 'SubmittedCharges': '172.00', 'PayableAmount': '91.80', 'ActualAllowed': '102.00', 'ContractualObligations': '', 'CoveredCharge': '102.00', 'CoveragePercent': '90%'}

In [20]:
tab_dict

[{'Submitted': 'D2332/Composite 3 Sr',
  'AltCode': '',
  'ToothNo': '09',
  'ServiceDate': '06/14/23',
  'SubmittedCharges': '172.00',
  'PayableAmount': '91.80',
  'ActualAllowed': '102.00',
  'ContractualObligations': '',
  'CoveredCharge': '102.00',
  'CoveragePercent': '90%'},
 {'Submitted': 'D2332/Composite 3 Sr',
  'AltCode': '',
  'ToothNo': '10',
  'ServiceDate': '06/14/23',
  'SubmittedCharges': '172.00',
  'PayableAmount': '91.80',
  'ActualAllowed': '102.00',
  'ContractualObligations': '',
  'CoveredCharge': '102.00',
  'CoveragePercent': '90%'}]

In [ ]:
# dfs = []
# x2 = 0
# for text_d in text_list:
#     x = text_d['cordx']
#     if x2<x:
#         x2 = text_d['cordx']
# x2 = x2+20      
# for i in range(len(text_list)):
#     x1 = y1 = y2 = ''
#     if 'Line' in text_list[i]['text']:
#         print("Line", text_list[i]['text'])
#         x1 = text_list[i]['cordx']
#         y1 = text_list[i]['cordy']
#         page_number = text_list[i]['page'])
#         for j in range(i,len(text_list)):
#             if 'BENEFIT SUMMARY' in text_list[j]['text']:
#                 print("Bene", text_list[j]['text'])
#                 page = int(text_list[j]['page'])
#                 y2 = text_list[j]['cordy']
#                 print(f"x1 = {x1}, y1 = {y1}, x2 = {x2}, y2 = {y2}")
#                 tabula_dfs = tabula.read_pdf(pdf_path, guess=False, pages=page , stream=True, encoding="utf-8",
#                                  area=(y1, x1, y2, x2), multiple_tables=True)
#                 dfs.append(tabula_dfs[0])
                
#                 break